Add generated numbers
intergiro/verification-example pull request #12
Opened 2022-07-01 08:01 UTC by robinnedergard

2022-07-01 08:23 UTC, Magnus93 requested changes

2022-07-01 08:23 UTC, Magnus93 commented on redirect.html
> +</html>
Add new line

2022-07-05 07:38 UTC, nilssonemma approved these changes

2022-07-08 07:56 UTC, Magnus93 approved these changes

2022-07-08 07:57 UTC, merged